//! The canonical DunneNote Format schema.
//!
//! `schema/v18.sql` is generated by DunneNote from a freshly created notebook and copied here
//! verbatim; it is never edited by hand. This library never ships migrations: notebooks at an
//! older schema must be opened in DunneNote once to upgrade them.

use rusqlite::Connection;

/// The `PRAGMA user_version` this library reads and writes.
pub const SCHEMA_VERSION: u32 = 18;

/// The `format_version` a notebook created at [`SCHEMA_VERSION`] carries in `format.json`.
pub const FORMAT_VERSION: &str = "0.18.0";

/// SHA-256 of `schema/v18.sql` as published. Changing the schema file without changing this
/// constant fails the test suite, so a schema change is always a deliberate, reviewed edit.
pub const SCHEMA_SHA256: &str = "dcead3a7cff689b43691fc41d2ab4611ce3355d7a2b8f37152e8b7b95186a433";

/// `CREATE` statements for an empty notebook database at [`SCHEMA_VERSION`].
pub const SCHEMA_SQL: &str = include_str!("../../../schema/v18.sql");

/// Create the full schema in an empty database and stamp `user_version`, in one transaction.
pub fn create_schema(conn: &mut Connection) -> rusqlite::Result<()> {
    let tx = conn.transaction()?;
    tx.execute_batch(SCHEMA_SQL)?;
    tx.pragma_update(None, "user_version", SCHEMA_VERSION)?;
    tx.commit()
}
